# Generated by Django 4.1.3 on 2022-12-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('biography', models.TextField(max_length=10000)),
                ('castcrewURL', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=10000)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('imdb_r', models.FloatField()),
                ('country', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('movieURL', models.URLField(max_length=500)),
                ('castcrews', models.ManyToManyField(to='brDbproject.castcrew')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=10000)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brDbproject.movies')),
            ],
        ),
    ]
