# Generated by Django 4.1.3 on 2022-12-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brDbproject', '0002_reviews_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='coverURL',
            field=models.URLField(default='https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
