# Generated by Django 4.1.3 on 2022-12-28 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brDbproject', '0003_movies_coverurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castcrew',
            name='role',
            field=models.CharField(choices=[('Director', 'Director'), ('Actor', 'Actor'), ('Writer', 'Writer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdb_r',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(error_messages={'required': 'my required msg..'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
